apiVersion: app/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-secret
          mountPath: /etc/nginx/secret
      volumes:
      - name: nginx-secret
        secret:
          secretName: nginx-secret