apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret-stringdata
type: Opaque
stringData:
  DB_HOST: mysql://db-primary.company.internal:3306/development_data
  DB_HOST_READONLY: mysql://db-replica.company.internal:3306/development_data